import { Inter } from "next/font/google";
import "./globals.css";
import { StatCards } from "../components/Dashboard/StatCards";
import { Sidebar } from "../components/Sidebar/Sidebar"
import { TopBar } from "../components/Dashboard/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-stone-950 flex bg-stone-100 flex`}>
                   <Sidebar />
             <div className="flex flex-1 flex-col">
                    <TopBar />
              

              <StatCards />
        
        {children}
             </div>
      </body>
    </html>
  );
}
